#!/bin/bash
################
# Made by MSz Msz MSz
# "You know me I came to see "
# "What secondary structure is to be"
####################################

# File1=find . -type f -name "*R1_001.fastq.gz"
# File2=*_R2_001.fastz.gz

FILES=$(find *.fastq.gz)
Dir=${PWD##*/}
TRIM=$(find ~/Trimmomatic-0.39/ -name "trimmomatic-0.39.jar")

echo $FILES
echo $Dir

java \
-jar ${TRIM} \
PE -phred33 \
$FILES \
${Dir}_output_R1_paired.fastq.gz ${Dir}_output_R1_unpaired.fastq.gz \
${Dir}_output_R2_paired.fastq.gz ${Dir}_output_R2_unpaired.fastq.gz \
ILLUMINACLIP:../NexteraPE-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
